### ISSUE TITLE
invalid character '}' after top-level value

### ISSUE THREAD

**Issue by halostatue** [cbuschka/tfvm#38]
* [x] This is a bug report

### Expected behavior

```console
$ terraform plan -out plan
# normal terraform output
```

### Actual behavior

```console
$ terraform plan -out plan
invalid character '}' after top-level value
```

### Steps to reproduce the behavior

I have clue what causes this to happen, but it appears that `CACHE/state.json` sometimes gets an *additional* `}` appended. I usually fix it by doing:

```
rm -rf ~/Library/Caches/tfvm/v1/
```

Everything works correctly for an indeterminate amount of time after that.

I’m using `tfvm` symlinked as `terraform`. There are two things to note:

1. I usually have multiple tabs open in my terminal and may be running multiple `terraform` commands in separate environment directories.
2. I am using fish with IlanCosman/tide, which is an asynchronous smart prompt that will run `terraform --version` to include terraform version information in the prompt.

My *theory* is that multiple versions of `tfvm` are running and writing to the state file at the same time, resulting in munged output.

**Output of `tfvm info`:**

```
Tfvm version is v0.22.0.
Built from commitish a9eae97, on 2021-09-27 17:40:08+02:00 for darwin/arm64.
OS is darwin, arch is arm64.
Cache dir is /Users/austin/Library/Caches/tfvm.
```

**Comment by halostatue** [comment]
It happened again just a few minutes after it happened this time.

``console
$ tfvm info
invalid character '}' after top-level value
```

**Output of `TF_LOG=trace tfvm <your command>`:**

```console
TF_LOG=trace tfvm info
invalid character '}' after top-level value
```

A subset of my state file:

```json
{
 "lastUpdateTime": "2022-11-03T11:12:32.69432-04:00",
 "terraformReleases": [
    {
     "os": "windows",
     "arch": "386",
     "download_path": "/terraform/0.11.5/terraform_0.11.5_windows_386.zip",
     "sha256_checksum": "47f6b634c78c27ae0f765817cc80a4411f91bdf7f4e593f8d83abcb58290a710"
    },
    {
     "os": "windows",
     "arch": "amd64",
     "download_path": "/terraform/0.11.5/terraform_0.11.5_windows_amd64.zip",
     "sha256_checksum": "c16be99bae3b252875ff58749adc7d4d32e25d2fe3d858d0090018f3b82d7aa"
    }
   ]
  }
 ]
}}
```

Removing the final `}` fixes everything…for now.

I *might* suggest that if JSON parsing fails on `state.json`, rather than `panic`ing, starting from a clean version might be the best choice.

**Comment by cbuschka** [comment]
Hey Austin, thanks for reporting this. Yes, when I think about it, it totally makes sense. I will deal with it when I have made it through my second covid infection (no worries, it's all o.k.). A solution could be switching to atomic writes (via natefinch/atomic for example) so no file corruptions can occur. See you soon, Conni

**Comment by cbuschka** [comment]
Hey @halostatue I have just released v0.24.0, which should fix the issue.

The state is written to a temp file and subsequently move in an atomic way. So when tfvm is run concurrently either the first or the second should "win" in a consistent way.

Looking forward to hear your feedback.

Conni

**Comment by halostatue** [comment]
I’m on vacation right now, so it will be a couple of weeks before there’s a chance of this showing up again.

**Comment by cbuschka** [comment]
@halostatue No hurry, enjoy your vacation!

**Comment by halostatue** [comment]
Apologies. I thought that I had upgraded `tfvm`, but I had not and I was coming to tell you that the problem still existed (I had seen it last week). I expect to be doing a bit more Terraform work in the new year, so I should have this tested properly by about January 15.

**Comment by cbuschka** [comment]
Hey Austin, thank you for coming back. Hope you have enyojed your vacation.
No need to hurry. Best Conni

**Comment by halostatue** [comment]
This appears to be fixed.

**Comment by cbuschka** [comment]
Hey @halostatue thanks for the verification. Looking forward to hear from you :) Best Conni
